# Generated by Django 3.0.2 on 2020-04-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A +ve'), ('B+', 'B +ve'), ('AB+', 'AB +ve'), ('O+', 'O +ve'), ('A-', 'A -ve'), ('B-', 'B -ve'), ('AB-', 'AB -ve'), ('O-', 'O -ve')], max_length=3),
        ),
    ]
