# Generated by Django 3.0.2 on 2020-04-25 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200425_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='email',
        ),
    ]
