# Generated by Django 3.0.2 on 2020-04-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_userprofileinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
