# Generated by Django 3.0.2 on 2020-04-25 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20200425_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_img', models.ImageField(upload_to='blog_pics')),
                ('desc', models.TextField(max_length=255)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
