# Generated by Django 3.0.2 on 2020-04-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20200425_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at']},
        ),
    ]
