# Generated by Django 3.0.2 on 2020-04-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20200425_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_img',
            field=models.ImageField(blank=True, upload_to='blog_pics'),
        ),
    ]
