# Generated by Django 3.0.2 on 2020-04-27 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20200425_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
    ]
