# Generated by Django 3.0.2 on 2020-04-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_newrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrequest',
            name='city',
            field=models.CharField(default='Bengaluru', max_length=128),
        ),
        migrations.AddField(
            model_name='newrequest',
            name='name',
            field=models.CharField(default='tester', max_length=128),
        ),
        migrations.AddField(
            model_name='newrequest',
            name='title',
            field=models.CharField(default='Urgent Help', max_length=128),
        ),
    ]
