# Generated by Django 3.0.2 on 2020-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20200428_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrequest',
            name='doc',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
    ]
