# Generated by Django 3.0.2 on 2020-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_newrequest_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrequest',
            name='msg',
            field=models.TextField(max_length=1024),
        ),
    ]
