# Generated by Django 2.2.10 on 2020-05-01 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_auto_20200428_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 5, 31, 12, 696976, tzinfo=utc)),
        ),
    ]
